package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("github.token", "credentialsJSON:c4043f5a-4055-4d3c-963e-936f91d93f8e")
        }
        update {
            password("github.token", "credentialsJSON:004e5420-f6ac-4f08-bc7f-45318eb343da")
        }
    }
}
